commit on 'code-journey'
collab-community/journey-book pull request #104
Opened 2022-08-04 14:55 UTC by Demilade-Ayoola

I added my code journey, followed the guidelines and also added my data to the Data.json

I made sure of the following:
-  My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
-  My changes generate no new warnings
-  Any dependent changes have been merged and published in downstream modules

2022-08-04 15:14 UTC, KendallDoesCoding reviewed
You haven't added your data in the Data.json file!

2022-08-04 15:35 UTC, Demilade-Ayoola commented
> 

I have commited the changes in the Data.Json file

2022-08-04 15:47 UTC, KendallDoesCoding commented
> > 
> 
> I have commited the changes in the Data.Json file

Thank you!

2022-08-04 15:53 UTC, KendallDoesCoding requested changes
fix typos, grammer.

2022-08-04 15:53 UTC, KendallDoesCoding commented on journeys/Demilade-Ayoola.md
> +- My name is Demilade and i'm from Lagos, Nigeria, I am a front-end web developer, A demographer and Data analyst
```suggestion
- My name is Demilade and I'm from Lagos, Nigeria. I am a front-end web developer. A demographer and Data analyst.
```

2022-08-04 15:53 UTC, KendallDoesCoding commented on journeys/Demilade-Ayoola.md
> +- My hobbies include travelling, coding, and playing sports like Tennis and Soccer
```suggestion
- My hobbies include traveling, coding, and playing sports like Tennis and Soccer.
```

2022-08-04 15:53 UTC, KendallDoesCoding commented on journeys/Demilade-Ayoola.md
> +- I am currently learning a couple of programming languages and using them to build projects to profer solutions and solve problems
```suggestion
- I am currently learning a couple of programming languages and using them to build projects to proper solutions and solve problems.
```
```

2022-08-04 15:53 UTC, KendallDoesCoding commented on journeys/Demilade-Ayoola.md
> +- I started learning coding in june 2021, when i wrote my first "Hello World"
```suggestion
- I started learning coding in June 2021, when I wrote my first "Hello World".
```

2022-08-04 15:53 UTC, KendallDoesCoding commented on journeys/Demilade-Ayoola.md
> +- I was taught HTML, CSS, Bootstrap within two months which i designed some projects. My learning course was interrupted for about 5 months due to my academics, but i returned back to continue learni
```suggestion
- I was taught HTML, CSS, and Bootstrap within two months, of which I designed some projects. My learning course was interrupted for about 5 months due to my academics, but I returned back to continue learning.
```

2022-08-04 15:53 UTC, KendallDoesCoding commented on journeys/Demilade-Ayoola.md
> +- I also learnt JavaScript and worked on some projects like Beat-maker project,Weather app, a travel website, To-do List. I learnt how to make animations using GSAP library and Scrollmagic which i us
```suggestion
- I also learned JavaScript and worked on some projects like Beat-maker project, Weather app, a travel website, To-do List. I learned how to make animations using GSAP library and Scrollmagic which i used effectively in the travel site.
```

2022-08-04 15:53 UTC, KendallDoesCoding commented on journeys/Demilade-Ayoola.md
> +- I am currently learning React-js and I have built a Banking App and also an E-commerce app.
```suggestion
- I am currently learning React-js and I have built a Banking App and also an E-commerce App.
```

2022-08-04 15:53 UTC, KendallDoesCoding commented on journeys/Demilade-Ayoola.md
> +- I am currently looking for an internship oppotunities to get more knowledge and experience as a Software Developer
```suggestion
- I am currently looking for an internship opportunities to get more knowledge and experience as a Software Developer.
```

2022-08-06 08:12 UTC, KendallDoesCoding commented
Please commit changes requested at the earliest @Demilade-Ayoola

2022-08-08 10:32 UTC, Demilade-Ayoola commented
I have commited the changes in the typo and errors

2022-08-08 10:45 UTC, KendallDoesCoding requested changes

2022-08-08 10:45 UTC, KendallDoesCoding commented on journeys/Demilade-Ayoola.md
> +- I also learned JavaScript and worked on some projects like Beat-maker project,Weather app, a travel website, To-do List. I learned how to make animations using GSAP library and Scrollmagic which i
```suggestion
- I also learned JavaScript and worked on some projects like Beat-maker project,Weather app, a travel website, To-do List. I learned how to make animations using GSAP library and Scrollmagic which I used effectively in the travel site. 
```

2022-08-08 10:46 UTC, KendallDoesCoding commented
@Demilade-Ayoola Please resolve conflicts in Data.json

2022-08-09 06:59 UTC, KendallDoesCoding approved these changes

2022-08-09 06:59 UTC, merged