Create PrateekSrivastava.md
collab-community/journey-book pull request #113
Opened 2022-08-09 20:14 UTC by Prateek-Srivastav

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-10 07:43 UTC, KendallDoesCoding requested changes
Please add your name to Data.json

2022-08-10 08:04 UTC, Prateek-Srivastav commented
done!

On Wed, 10 Aug 2022 at 13:14, Kendall ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Please add your name to Data.json
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/collab-community/journey-book/pull/113#pullrequestreview-1067817499>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASFYK6BOEBE4DLVOCZCELMTVYNMUJANCNFSM56CBNJ6Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-10 10:28 UTC, KendallDoesCoding requested changes

2022-08-10 10:28 UTC, KendallDoesCoding commented on journeys/PrateekSrivastava.md
> +- created a fully functioning job searching and placement android application for a startup.
```suggestion
- Created a fully functioning job searching and placement android application for a startup.
```

2022-08-10 10:28 UTC, KendallDoesCoding commented on journeys/PrateekSrivastava.md
> +- created backend of an e-commerce like startup from scratch involving all kindof functioning like CRUD requests, searching and hosting on AWS.
```suggestion
- Created backend of an e-commerce like startup from scratch involving all kind of functioning like CRUD requests, searching and hosting on AWS.
```

2022-08-10 10:28 UTC, KendallDoesCoding commented on journeys/PrateekSrivastava.md
> +- created other android applications as a project like recipe app and the shop app.
```suggestion
- Created other android applications as a project like recipe app and the shop app.
```

2022-08-10 10:29 UTC, KendallDoesCoding commented on journeys/PrateekSrivastava.md
> +# Other than coding , i love
```suggestion
# Other than coding , I love
```

2022-08-11 12:40 UTC, KendallDoesCoding commented on journeys/PrateekSrivastava.md
> +# Projects i have worked on
```suggestion
# Projects I have worked on
```

2022-08-11 12:41 UTC, KendallDoesCoding approved these changes

2022-08-11 12:41 UTC, merged

2022-08-11 12:41 UTC, KendallDoesCoding commented
Thanks for your contribution @Prateek-Srivastav! Woo-Hoo Your jourrney is now added