Add hover effect to user-card
collab-community/journey-book pull request #147
Opened 2022-10-02 14:34 UTC by devXprite

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### Preview :

https://user-images.githubusercontent.com/80192140/193459563-fbb4804c-12cc-4010-b591-f304a1a12bcc.mp4

2022-10-03 16:21 UTC, Adarsh-jaiss commented
- @vikasganiga05 please review this

2022-10-06 08:20 UTC, vikasganiga05 requested changes
When the user hovers on one card the other cards shift their position. I suggested changes below. Please check them out.

2022-10-06 08:20 UTC, vikasganiga05 commented on style.css
> +  border-width: 2px;
My suggestion is to remove this because other cards shift their position.
```suggestion

```

2022-10-06 08:20 UTC, vikasganiga05 commented on style.css
> +  filter: brightness(1.3);
This does not look good on the light theme.

2022-10-06 08:56 UTC, devXprite commented
@vikasganiga05  I Did the suggested changes!!

2022-10-07 18:49 UTC, vikasganiga05 approved these changes
It looks good to me. Thanks for your contribution :tada:

2022-10-07 18:52 UTC, merged