Created new file ShivamPathak99.md and updated Data.json
collab-community/journey-book pull request #180
Opened 2022-10-10 06:30 UTC by ShivamPathak99

## Description

Added ShivamPathak99.md in journeys and updated Data.json .

*Please consider it for Hacktoberfest*

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

2022-10-10 13:03 UTC, Adarsh-jaiss approved these changes

2022-10-10 13:04 UTC, Adarsh-jaiss commented
- @vikasganiga05  please fix this merge conflict!

2022-10-11 00:15 UTC, vikasganiga05 approved these changes
It looks good to me. Thanks for your contribution :tada:
- Thank you so much Shivam Pathak for sharing your journey till now.
- We are waiting for more contributions from you :green_heart:

Hi @Adarsh-jaiss , I resolved the merge conflicts. please share your thoughts on the journey file.

2022-10-11 00:48 UTC, vikasganiga05 requested changes
Hi @ShivamPathak99 , A small suggestion.

2022-10-11 00:48 UTC, vikasganiga05 commented on journeys/ShivamPathak99.md
> +<h1>Hi, this is Shivam Pathak☺️ </h1>
```suggestion
# [Shivam Pathak](https://github.com/ShivamPathak99)'s Journey
```

2022-10-12 02:40 UTC, vikasganiga05 commented on journeys/ShivamPathak99.md
> +<h1>Hi, this is Shivam Pathak☺️ </h1>
Hey, no changes are made :thinking:

2022-10-17 19:19 UTC, vikasganiga05 approved these changes
It looks good to me. Thanks for your contribution :tada:
- Thank you so much Shivam Pathak for sharing your journey till now.
- We are waiting for more contributions from you :green_heart:

2022-10-19 01:56 UTC, merged